CREATE DATABASE PhoneCaseECommerceDB
GO 
USE PhoneCaseeECommerceDB
GO 
 
CREATE TABLE [dbo].[Users](
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[PasswordHash] VARBINARY(MAX) NULL,
	[PasswordSalt] VARBINARY(MAX) NULL,
	[Fullname] NVARCHAR(MAX) NOT NULL,
	[PhoneNumber] VARCHAR(15) NULL,
	[Email] NVARCHAR(MAX) NULL,
)

GO

CREATE TABLE [dbo].[Vendors](
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(MAX) NULL,
)
GO

CREATE TABLE [dbo].[Models](
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(MAX) NULL,
	[VendorId] INT FOREIGN KEY REFERENCES Vendors(Id)NOT NULL,
)

GO

CREATE TABLE [dbo].[Colors](
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(MAX) NULL
)
GO

CREATE TABLE [dbo].[PhotoImages](
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[PhoneCaseId] INT FOREIGN KEY REFERENCES PhoneCases(Id)NOT NULL,
[Path] NVARCHAR(MAX) NULL
)


GO

CREATE TABLE [dbo].[UserImages](
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[UserId] INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
[Path] NVARCHAR(MAX) NULL
)

GO

CREATE TABLE [dbo].[PhoneCases](
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Price] DECIMAL(10,2) NOT NULL,
[Description] NVARCHAR(max)NULL,
[SellCount] INT NULL DEFAULT(0),
[Premium] NVARCHAR(20) NOT NULL DEFAULT 'Simple',
CONSTRAINT CHK_Premium CHECK (Premium IN ('Premium', 'Simple', 'Popular')),
[VendorId] INT FOREIGN KEY REFERENCES Vendors(Id) NOT NULL,
[ModelId] INT FOREIGN KEY REFERENCES Models(Id) NOT NULL,
[UserId] INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
)
GO

CREATE TABLE [dbo].[PhoneColors](
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[PhoneCaseId] INT FOREIGN KEY REFERENCES PhoneCases(Id)NOT NULL,
	[ColorId]INT FOREIGN KEY REFERENCES Colors(Id)NOT NULL
)

GO

CREATE TABLE [dbo].[Comments](
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Description] NVARCHAR(max)NULL,
	[PhoneCaseId] INT FOREIGN KEY REFERENCES PhoneCases(Id)NOT NULL,
[UserId] INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
)


GO

CREATE TABLE [dbo].[Favorites](
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[PhoneCaseId] INT FOREIGN KEY REFERENCES PhoneCases(Id)NOT NULL,
) 

GO

CREATE TABLE [dbo].[Orders](
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[TotalAmount] DECIMAL(10,2) NOT NULL,
	[OrderDate] DATETIME2(7) NOT NULL,
	[OrderStatus] NVARCHAR(50) NULL
)

GO

CREATE TABLE [dbo].[OrderDetails](
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[OrderId] INT FOREIGN KEY REFERENCES Orders(Id)NOT NULL,
		[PhoneCaseId] INT FOREIGN KEY REFERENCES PhoneCases(Id)NOT NULL,
		[Quantity] INT NOT NULL DEFAULT(0)
)

GO

CREATE TABLE [dbo].[Cart](
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[UserId] INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,	
[PhoneCaseId] INT FOREIGN KEY REFERENCES PhoneCases(Id)NOT NULL,
[Quantity] INT NULL DEFAULT(0),
)



