// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneCaseEcommerce.Entities.Models;

#nullable disable

namespace PhoneCaseEcommerce.Entities.Migrations
{
    [DbContext(typeof(PhoneCaseEcommerceDbContext))]
    [Migration("20240911133238_role")]
    partial class role
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PhoneCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Cart__3214EC071F8C1D69");

                    b.HasIndex("PhoneCaseId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Colors__3214EC07A5C8477E");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneCaseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Comments__3214EC07155F73D1");

                    b.HasIndex("PhoneCaseId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PhoneCaseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Favorite__3214EC0798DA10ED");

                    b.HasIndex("PhoneCaseId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Models__3214EC07E0721634");

                    b.HasIndex("VendorId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC07D8C9EBC5");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PhoneCaseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC07C711508A");

                    b.HasIndex("OrderId");

                    b.HasIndex("PhoneCaseId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.PhoneCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Premium")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Simple");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("SellCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PhoneCas__3214EC07D9FE143C");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId");

                    b.HasIndex("VendorId");

                    b.ToTable("PhoneCases");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.PhoneColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("PhoneCaseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PhoneCol__3214EC07F31D0FEE");

                    b.HasIndex("ColorId");

                    b.HasIndex("PhoneCaseId");

                    b.ToTable("PhoneColors");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.PhotoImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneCaseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PhotoIma__3214EC0787A656C9");

                    b.HasIndex("PhoneCaseId");

                    b.ToTable("PhotoImages");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07B9C0DEFC");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserImag__3214EC078C88E55D");

                    b.HasIndex("UserId");

                    b.ToTable("UserImages");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Vendors__3214EC0792E6B697");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Cart", b =>
                {
                    b.HasOne("PhoneCaseEcommerce.Entities.Models.PhoneCase", "PhoneCase")
                        .WithMany("Carts")
                        .HasForeignKey("PhoneCaseId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart__PhoneCaseI__5FB337D6");

                    b.HasOne("PhoneCaseEcommerce.Entities.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart__UserId__5EBF139D");

                    b.Navigation("PhoneCase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Comment", b =>
                {
                    b.HasOne("PhoneCaseEcommerce.Entities.Models.PhoneCase", "PhoneCase")
                        .WithMany("Comments")
                        .HasForeignKey("PhoneCaseId")
                        .IsRequired()
                        .HasConstraintName("FK__Comments__PhoneC__5165187F");

                    b.HasOne("PhoneCaseEcommerce.Entities.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Comments__UserId__52593CB8");

                    b.Navigation("PhoneCase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Favorite", b =>
                {
                    b.HasOne("PhoneCaseEcommerce.Entities.Models.PhoneCase", "PhoneCase")
                        .WithMany("Favorites")
                        .HasForeignKey("PhoneCaseId")
                        .IsRequired()
                        .HasConstraintName("FK__Favorites__Phone__5535A963");

                    b.Navigation("PhoneCase");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Model", b =>
                {
                    b.HasOne("PhoneCaseEcommerce.Entities.Models.Vendor", "Vendor")
                        .WithMany("Models")
                        .HasForeignKey("VendorId")
                        .IsRequired()
                        .HasConstraintName("FK__Models__VendorId__3A81B327");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.OrderDetail", b =>
                {
                    b.HasOne("PhoneCaseEcommerce.Entities.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Order__59FA5E80");

                    b.HasOne("PhoneCaseEcommerce.Entities.Models.PhoneCase", "PhoneCase")
                        .WithMany("OrderDetails")
                        .HasForeignKey("PhoneCaseId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Phone__5AEE82B9");

                    b.Navigation("Order");

                    b.Navigation("PhoneCase");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.PhoneCase", b =>
                {
                    b.HasOne("PhoneCaseEcommerce.Entities.Models.Model", "Model")
                        .WithMany("PhoneCases")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FK__PhoneCase__Model__46E78A0C");

                    b.HasOne("PhoneCaseEcommerce.Entities.Models.User", "User")
                        .WithMany("PhoneCases")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PhoneCase__UserI__47DBAE45");

                    b.HasOne("PhoneCaseEcommerce.Entities.Models.Vendor", "Vendor")
                        .WithMany("PhoneCases")
                        .HasForeignKey("VendorId")
                        .IsRequired()
                        .HasConstraintName("FK__PhoneCase__Vendo__45F365D3");

                    b.Navigation("Model");

                    b.Navigation("User");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.PhoneColor", b =>
                {
                    b.HasOne("PhoneCaseEcommerce.Entities.Models.Color", "Color")
                        .WithMany("PhoneColors")
                        .HasForeignKey("ColorId")
                        .IsRequired()
                        .HasConstraintName("FK__PhoneColo__Color__4E88ABD4");

                    b.HasOne("PhoneCaseEcommerce.Entities.Models.PhoneCase", "PhoneCase")
                        .WithMany("PhoneColors")
                        .HasForeignKey("PhoneCaseId")
                        .IsRequired()
                        .HasConstraintName("FK__PhoneColo__Phone__4D94879B");

                    b.Navigation("Color");

                    b.Navigation("PhoneCase");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.PhotoImage", b =>
                {
                    b.HasOne("PhoneCaseEcommerce.Entities.Models.PhoneCase", "PhoneCase")
                        .WithMany("PhotoImages")
                        .HasForeignKey("PhoneCaseId")
                        .IsRequired()
                        .HasConstraintName("FK__PhotoImag__Phone__4AB81AF0");

                    b.Navigation("PhoneCase");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.UserImage", b =>
                {
                    b.HasOne("PhoneCaseEcommerce.Entities.Models.User", "User")
                        .WithMany("UserImages")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserImage__UserI__403A8C7D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Color", b =>
                {
                    b.Navigation("PhoneColors");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Model", b =>
                {
                    b.Navigation("PhoneCases");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.PhoneCase", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("OrderDetails");

                    b.Navigation("PhoneColors");

                    b.Navigation("PhotoImages");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Comments");

                    b.Navigation("PhoneCases");

                    b.Navigation("UserImages");
                });

            modelBuilder.Entity("PhoneCaseEcommerce.Entities.Models.Vendor", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("PhoneCases");
                });
#pragma warning restore 612, 618
        }
    }
}
